import { createGlobalTheme, createThemeContract } from '@vanilla-extract/css';
import { $Palette, ColorPalette } from '@types';

const theme = createThemeContract({
  primary: null,
  surfaceTint: null,
  onPrimary: null,
  primaryContainer: null,
  onPrimaryContainer: null,
  secondary: null,
  onSecondary: null,
  secondaryContainer: null,
  onSecondaryContainer: null,
  tertiary: null,
  onTertiary: null,
  tertiaryContainer: null,
  onTertiaryContainer: null,
  error: null,
  onError: null,
  errorContainer: null,
  onErrorContainer: null,
  surface: null,
  onSurface: null,
  surfaceVariant: null,
  onSurfaceVariant: null,
  outline: null,
  outlineVariant: null,
  shadow: null,
  surfaceDim: null,
  surfaceContainer: null,
  disabled: null,
});

// Light Theme
createGlobalTheme("html[data-theme-mode='light']", theme, {
  primary: $Palette['Blue600'],
  surfaceTint: $Palette['Blue600'],
  onPrimary: $Palette['White'],
  primaryContainer: $Palette['Blue100'],
  onPrimaryContainer: $Palette['Blue900'],
  secondary: $Palette['Cyan600'],
  onSecondary: $Palette['White'],
  secondaryContainer: $Palette['Cyan200'],
  onSecondaryContainer: $Palette['Cyan900'],
  tertiary: $Palette['Lime600'],
  onTertiary: $Palette['White'],
  tertiaryContainer: $Palette['Lime200'],
  onTertiaryContainer: $Palette['Lime900'],
  error: $Palette['Error'],
  onError: $Palette['White'],
  errorContainer: $Palette['Orange100'],
  onErrorContainer: $Palette['Orange900'],
  surface: $Palette['Gray50'],
  onSurface: $Palette['Gray900'],
  surfaceVariant: $Palette['Gray200'],
  onSurfaceVariant: $Palette['Gray700'],
  outline: $Palette['Gray400'],
  outlineVariant: $Palette['Gray700'],
  shadow: $Palette['Black'],
  surfaceDim: 'rgba(0, 0, 0, 0.6)',
  surfaceContainer: $Palette['Gray100'],
  disabled: $Palette['Gray300'],
});

// Dark Theme
createGlobalTheme("html[data-theme-mode='dark']", theme, {
  primary: $Palette['Blue900'],
  surfaceTint: $Palette['Blue900'],
  onPrimary: $Palette['Gray50'],
  primaryContainer: $Palette['Blue700'],
  onPrimaryContainer: $Palette['Gray200'],
  secondary: $Palette['Teal700'],
  onSecondary: $Palette['Gray50'],
  secondaryContainer: $Palette['Teal500'],
  onSecondaryContainer: $Palette['Gray200'],
  tertiary: $Palette['Green700'],
  onTertiary: $Palette['Gray50'],
  tertiaryContainer: $Palette['Green500'],
  onTertiaryContainer: $Palette['Gray200'],
  error: $Palette['Error'],
  onError: $Palette['Gray50'],
  errorContainer: $Palette['Orange100'],
  onErrorContainer: $Palette['Orange900'],
  surface: $Palette['Gray900'],
  onSurface: $Palette['Gray100'],
  surfaceVariant: $Palette['Gray800'],
  onSurfaceVariant: $Palette['Gray300'],
  outline: $Palette['Gray700'],
  outlineVariant: $Palette['Gray300'],
  shadow: $Palette['Black'],
  surfaceDim: 'rgba(0, 0, 0, 0.6)',
  surfaceContainer: $Palette['Gray800'],
  disabled: $Palette['Gray700'],
});

const root = createGlobalTheme<ColorPalette>(':root', $Palette);

export default { ...root, ...theme };
