import Script from "next/script";
import "./globals.css";
import "@gugbab-integrated-admin-poc/ui-sass/public/styles/components.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <Script src="/__ENV.js" strategy="beforeInteractive" />
      </head>
      <body>{children}</body>
    </html>
  );
}
