export type ColorTypes =
  | 'logo-main-red'
  | 'logo-sub-lime'
  | 'secondary-navy'
  | 'secondary-navy-blue'
  | 'secondary-green'
  | 'accent-yellow'
  | 'accent-negative-red'
  | 'accent-red'
  | 'accent-orange'
  | 'grayscale-gray900'
  | 'grayscale-gray800'
  | 'grayscale-gray700'
  | 'grayscale-gray500'
  | 'grayscale-gray400'
  | 'grayscale-gray300'
  | 'grayscale-gray200'
  | 'grayscale-gray100'
  | 'grayscale-gray50'
  | 'redscale-red900'
  | 'redscale-red700'
  | 'redscale-red600'
  | 'redscale-red500'
  | 'redscale-red400'
  | 'redscale-red300'
  | 'redscale-red200'
  | 'redscale-red100'
  | 'redscale-red50'
  | 'white'
  | 'black'
  | 'gray'
  | 'disable'
  | 'contents-bg'
  | 'primary';

export type BulletColor = 'grayscale-gray900' | 'grayscale-gray700';
